# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('INSCRIPTION_ELEVE', 'Inscription Élève'), ('PAIEMENT_MENSUALITE', 'Paiement Mensualité'), ('PAIEMENT_VALIDATION', 'Validation Paiement'), ('REJET_PAIEMENT', 'Rejet Paiement'), ('RAPPEL_PAIEMENT', 'Rappel Paiement'), ('INFO_GENERALE', 'Information Générale')], max_length=30)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('SYSTEM', 'System')], default='SYSTEM', max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('ERREUR', 'Erreur'), ('EN_ATTENTE', 'En Attente')], default='EN_ATTENTE', max_length=15)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_lu', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.customuser')),
                ('eleve_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='eleves.eleve')),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='TemplateNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('INSCRIPTION_ELEVE', 'Inscription Élève'), ('PAIEMENT_MENSUALITE', 'Paiement Mensualité'), ('PAIEMENT_VALIDATION', 'Validation Paiement'), ('REJET_PAIEMENT', 'Rejet Paiement'), ('RAPPEL_PAIEMENT', 'Rappel Paiement')], max_length=30, unique=True)),
                ('sujet_email', models.CharField(max_length=200)),
                ('template_email', models.TextField()),
                ('template_sms', models.CharField(max_length=500)),
                ('variables_disponibles', models.TextField(help_text='Variables disponibles: {nom_eleve}, {prenom_eleve}, {matricule}, {classe}, {montant}, {date}, {parent_nom}')),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
    ]
