# Generated by Django 5.0.6 on 2026-03-03 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(choices=[('LYCEE', 'Lycée'), ('COLLEGE', 'Collège'), ('PRIMAIRE', 'Primaire')], default='LYCEE', max_length=20)),
                ('annee_scolaire', models.CharField(default='2023-2024', max_length=9)),
                ('frais_mensuel_attendu', models.DecimalField(decimal_places=0, default=0, help_text='Montant en GNF', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('RENVOYE', 'Renvoyé')], default='ACTIF', max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves_photos/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='eleves.classe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_eleve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('adresse', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('enfants', models.ManyToManyField(blank=True, related_name='parents', to='eleves.eleve')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_parent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
