# Generated by Django 5.0.6 on 2026-03-03 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du cycle')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.RemoveField(
            model_name='classe',
            name='niveau',
        ),
        migrations.AddField(
            model_name='classe',
            name='branche',
            field=models.CharField(choices=[('SM', 'Sciences Mathématiques'), ('SS', 'Sciences Sociales'), ('SE', 'Sciences Expérimentales'), ('GEN', 'Général')], default='GEN', max_length=20),
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du niveau')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('est_annee_examen', models.BooleanField(default=False, help_text='CEE, BEPC, BAC')),
                ('label_examen', models.CharField(blank=True, max_length=50, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='eleves.cycle')),
            ],
            options={
                'ordering': ['cycle__ordre', 'ordre'],
                'unique_together': {('cycle', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau_scolaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='eleves.niveauscolaire'),
        ),
    ]
