# Generated by Django 5.0.6 on 2026-03-03 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='badges/qrcodes/')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='eleves.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_scanne', models.CharField(blank=True, max_length=100)),
                ('resultat', models.CharField(choices=[('OK', 'Accès Autorisé'), ('INVALIDE', 'Badge Invalide'), ('INACTIF', 'Badge Désactivé'), ('ECHEC_FINANCE', 'Bloqué (Scolarité)')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.CharField(blank=True, help_text="Nom/ID de l'agent ou de la borne", max_length=100)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='badges.badge')),
            ],
        ),
    ]
