# Generated by Django 5.0.6 on 2026-03-03 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('MENSUALITE', 'Mensualité'), ('TRIMESTRE', 'Trimestre'), ('AUTRE', 'Autre Frais')], default='MENSUALITE', max_length=20)),
                ('mois_concerne', models.DateField(blank=True, help_text='Premier jour du mois concerné', null=True)),
                ('montant_attendu', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('est_solde', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_scolarite', to='eleves.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(db_index=True, default=uuid.uuid4, max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('methode', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement Bancaire'), ('MOMO', 'MTN MoMo'), ('ORANGE', 'Orange Money')], max_length=20)),
                ('statut', models.CharField(choices=[('ATTENTE', 'En Attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='ATTENTE', max_length=15)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='eleves.eleve')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
