# Generated by Django 5.0.6 on 2026-03-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du chapitre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chapitre du règlement',
                'verbose_name_plural': 'Chapitres du règlement',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé (ex: Réussite au CEE)')),
                ('value', models.FloatField(verbose_name='Valeur (%)')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistique de réussite',
                'verbose_name_plural': 'Statistiques de réussite',
            },
        ),
    ]
