# Generated by Django 5.0.6 on 2026-03-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CEE', 'CEE'), ('BEPC', 'BEPC'), ('BAC', 'BAC')], max_length=10)),
                ('annee', models.IntegerField()),
                ('total_candidats', models.PositiveIntegerField()),
                ('total_admis', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('role', models.CharField(max_length=100, verbose_name='Poste / Fonction')),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='successstat',
            name='value',
            field=models.FloatField(help_text='Sera écrasé par le calcul automatique si un examen est lié', verbose_name='Valeur (%)'),
        ),
    ]
