# Generated by Django 5.0.6 on 2026-03-03 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('annee_scolaire', models.CharField(default='2023-2024', max_length=9)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Note sur 20', max_digits=4)),
                ('appreciation', models.CharField(blank=True, max_length=255)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='notes.matiere')),
                ('professeur', models.ForeignKey(limit_choices_to={'role': 'PROF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='notes.trimestre')),
            ],
            options={
                'unique_together': {('eleve', 'matiere', 'trimestre')},
            },
        ),
    ]
